export enum AuthErrorCode {
    AUTH_GOOGLE_FAILED = 'AUTH_GOOGLE_FAILED',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_REFRESH_INVALID = 'AUTH_REFRESH_INVALID',
    AUTH_REFRESH_EXPIRED = 'AUTH_REFRESH_EXPIRED',
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
}